name: Weekly Slack Groups

on:
  schedule:
    - cron: "54 23 * * SUN"  # 월요일 오전 8시 54분 (큐에 대기 쌓여서 실제 실행 시간은 더 느림)
  workflow_dispatch:

jobs:
  send-groups:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python group_sender.py
        env: # 환경 변수
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_MEMBER_CHANNEL_ID: ${{ secrets.SLACK_MEMBER_CHANNEL_ID }}
          SLACK_TARGET_CHANNEL_ID: ${{ secrets.SLACK_TARGET_CHANNEL_ID }}
